require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '11.0'

project 'ReactNativeBase',
        'DevelopDebug' => :debug,
        'DevelopRelease' => :release,
        'StagingDebug' => :debug,
        'StagingRelease' => :release,
        'ProductDebug' => :debug,
        'ProductRelease' => :release

target 'ReactNativeBase' do
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    # to enable hermes on iOS, change `false` to `true` and then install pods
    :hermes_enabled => false
  )


  permissions_path = '../node_modules/react-native-permissions/ios'
  pod 'Permission-Camera', :path => "#{permissions_path}/Camera"

  target 'ReactNativeBaseTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable the next line.
  use_flipper!()

  ENVFILES = {
    'DevelopDebug' => '$(PODS_ROOT)/../../.env.develop',
    'DevelopRelease' => '$(PODS_ROOT)/../../.env.develop',
    'StagingDebug' => '$(PODS_ROOT)/../../.env.release',
    'StagingRelease' => '$(PODS_ROOT)/../../.env.release',
    'ProductDebug' => '$(PODS_ROOT)/../../.env.product',
    'ProductRelease' => '$(PODS_ROOT)/../../.env.product',
  }
  post_install do |installer|
    react_native_post_install(installer)
      installer.pods_project.build_configurations.each do |config|
        config.build_settings["EXCLUDED_ARCHS[sdk=iphonesimulator*]"] = "arm64"
      end
  end
end
